### ISSUE TITLE
resize image before upload

### ISSUE THREAD

**Issue by juliamazur** [juliamazur/cookking-react-firebase#2]
npm i @google-cloud/storage
npm i sharp
npm install --save fs-extra

**Comment by juliamazur** [comment]
https://angularfirebase.com/lessons/image-thumbnail-resizer-cloud-function/

looks great bu doesnt work ATM:
https://github.com/firebase/firebase-admin-node/issues/358

**Comment by SundarGowtham** [comment]
I have been trying to get code from his video to work. I keep getting the same error that:

@google-cloud/storage/build/src/index"' has no exported member 'Bucket'
